name: Update RSS Feed

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes
  push:
    branches:
      - main  # Change to your default branch if different

jobs:
  update-rss:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai==1.14.2 PyGithub feedparser requests python-dotenv

      - name: List directory for debug
        run: ls -R  # 列出所有文件和目录

      - name: Run script
        env:
          API_SECRET_KEY: ${{ secrets.API_SECRET_KEY }}
          BASE_API_URL: ${{ secrets.BASE_API_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python news.py  # 确保你的Python脚本文件名和路径正确
